spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/moing
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true
    show-sql: true

jwt:
  secret: ${JWT_SECRET}
  access-token-expiration: 3600000
  refresh-token-expiration: 1209600000

kakao:
  api-key: ${KAKAO_API_KEY:}
  user-info-url: https://kapi.kakao.com/v2/user/me

naver:
  api-key-id: ${NAVER_API_KEY_ID:}
  api-key: ${NAVER_API_KEY:}

aws:
  s3:
    access-key: ${AWS_ACCESS_KEY}
    secret-key: ${AWS_SECRET_KEY}
    region: ap-northeast-2
    bucket: moing-reviews

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
  api-docs:
    path: /v3/api-docs